### ISSUE TITLE
have no binary version

### ISSUE THREAD

**Issue by helpxiaoshan** [hiboxsystems/redis_sentinel_exporter#1]
你好，我用 go build 编译不通过，提示reading github.com/gomodule/redigo/go.mod at revision v1.8.2: unknown revision v1.8.2
可否提供个已经编译好，centos7上直接能运行的包？不胜感激。

**Comment by perlun** [comment]
Hi @helpxiaoshan. Unfortunately I don't know Chinese so it's very hard for me to read your message. However, I did understand the subject line.

The reason why this repository does not have any binary version is that it's a git-only backup of the now-deleted GitHub repo previously found at https://github.com/leominov/redis_sentinel_exporter/.

We don't know why it got removed, but since we use the exporter ourselves, we decided to push up the git code (which we had a local backup of) to this repo to preserve it.

I just checked and https://web.archive.org/web/20200905070524/https://github.com/leominov/redis_sentinel_exporter/ does seem to have a version stored as well. I checked and the latest release seems to be downloadable from there. :tada: Please give it a try and see if it meets your needs.

I'll close this issue now, thanks for asking. :+1:

**Comment by perlun** [comment]
In the intent of helping the community, I published a new version now with some binaries in this repo: https://github.com/hiboxsystems/redis_sentinel_exporter/releases/tag/v1.7.2
